//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.6.</auto-generated>
//------------------------------------------------------------------------------
using System;

namespace RideShare.LLBLGEN.TypedListClasses
{
	/// <summary>Class which represents a row in the typed list 'MyTypedList'.</summary>
	/// <remarks>Contains the following entity definition(s):
	/// Entity: Tbladdress. <br/>
	/// Entity: Tblcontact. <br/>
	/// Entity: TblContactType. <br/>
	/// Entity: TblRide. <br/>
	/// Entity: TblRideRequest. <br/>
	/// Entity: TblUser. <br/>
	/// </remarks>
	public partial class MyTypedListTypedListRow 
	{
		partial void OnCreated();
				
		/// <summary>Initializes a new instance of the <see cref="MyTypedListTypedListRow"/> class.</summary>
		public MyTypedListTypedListRow()
		{
			OnCreated();
		}

		/// <summary>Gets the AddressCreateDate field. Mapped onto 'Tbladdress.AddressCreateDate'</summary>
		public System.DateTime AddressCreateDate { get; set; }
		
		/// <summary>Gets the AddressGuid field. Mapped onto 'Tbladdress.AddressGuid'</summary>
		public System.Guid AddressGuid { get; set; }
		
		/// <summary>Gets the AddressUpdateDate field. Mapped onto 'Tbladdress.AddressUpdateDate'</summary>
		public System.DateTime AddressUpdateDate { get; set; }
		
		/// <summary>Gets the City field. Mapped onto 'Tbladdress.City'</summary>
		public System.String City { get; set; }
		
		/// <summary>Gets the PostalCode field. Mapped onto 'Tbladdress.PostalCode'</summary>
		public Nullable<System.Int32> PostalCode { get; set; }
		
		/// <summary>Gets the State field. Mapped onto 'Tbladdress.State'</summary>
		public System.String State { get; set; }
		
		/// <summary>Gets the Street1 field. Mapped onto 'Tbladdress.Street1'</summary>
		public System.String Street1 { get; set; }
		
		/// <summary>Gets the Street2 field. Mapped onto 'Tbladdress.Street2'</summary>
		public System.String Street2 { get; set; }
		
		/// <summary>Gets the UserGuid field. Mapped onto 'Tbladdress.UserGuid'</summary>
		public System.Guid UserGuid { get; set; }
		
		/// <summary>Gets the ContactCreateDate field. Mapped onto 'Tblcontact.ContactCreateDate'</summary>
		public System.DateTime ContactCreateDate { get; set; }
		
		/// <summary>Gets the ContactGuid field. Mapped onto 'Tblcontact.ContactGuid'</summary>
		public System.Guid ContactGuid { get; set; }
		
		/// <summary>Gets the ContactType field. Mapped onto 'Tblcontact.ContactType'</summary>
		public Nullable<System.Guid> ContactType { get; set; }
		
		/// <summary>Gets the ContactUpdateDate field. Mapped onto 'Tblcontact.ContactUpdateDate'</summary>
		public System.DateTime ContactUpdateDate { get; set; }
		
		/// <summary>Gets the ContactValue field. Mapped onto 'Tblcontact.ContactValue'</summary>
		public System.String ContactValue { get; set; }
		
		/// <summary>Gets the IsActive field. Mapped onto 'Tblcontact.IsActive'</summary>
		public System.String IsActive { get; set; }
		
		/// <summary>Gets the UserGuid1 field. Mapped onto 'Tblcontact.UserGuid'</summary>
		public System.Guid UserGuid1 { get; set; }
		
		/// <summary>Gets the ContactType1 field. Mapped onto 'TblContactType.ContactType'</summary>
		public System.String ContactType1 { get; set; }
		
		/// <summary>Gets the ContactTypeCreateDate field. Mapped onto 'TblContactType.ContactTypeCreateDate'</summary>
		public System.DateTime ContactTypeCreateDate { get; set; }
		
		/// <summary>Gets the ContactTypeGuid field. Mapped onto 'TblContactType.ContactTypeGuid'</summary>
		public System.Guid ContactTypeGuid { get; set; }
		
		/// <summary>Gets the ContactTypeUpdateDate field. Mapped onto 'TblContactType.ContactTypeUpdateDate'</summary>
		public System.DateTime ContactTypeUpdateDate { get; set; }
		
		/// <summary>Gets the RideCreateDate field. Mapped onto 'TblRide.RideCreateDate'</summary>
		public System.DateTime RideCreateDate { get; set; }
		
		/// <summary>Gets the RideEndAddressGuid field. Mapped onto 'TblRide.RideEndAddressGuid'</summary>
		public System.Guid RideEndAddressGuid { get; set; }
		
		/// <summary>Gets the RideEndDateTime field. Mapped onto 'TblRide.RideEndDateTime'</summary>
		public System.DateTime RideEndDateTime { get; set; }
		
		/// <summary>Gets the RideFromGuid field. Mapped onto 'TblRide.RideFromGuid'</summary>
		public System.Guid RideFromGuid { get; set; }
		
		/// <summary>Gets the RideGuid field. Mapped onto 'TblRide.RideGuid'</summary>
		public System.Guid RideGuid { get; set; }
		
		/// <summary>Gets the RideStartAddressGuid field. Mapped onto 'TblRide.RideStartAddressGuid'</summary>
		public System.Guid RideStartAddressGuid { get; set; }
		
		/// <summary>Gets the RideStartDateTime field. Mapped onto 'TblRide.RideStartDateTime'</summary>
		public System.DateTime RideStartDateTime { get; set; }
		
		/// <summary>Gets the RideToGuid field. Mapped onto 'TblRide.RideToGuid'</summary>
		public System.Guid RideToGuid { get; set; }
		
		/// <summary>Gets the RideUpdateDate field. Mapped onto 'TblRide.RideUpdateDate'</summary>
		public System.DateTime RideUpdateDate { get; set; }
		
		/// <summary>Gets the RequestCreateDate field. Mapped onto 'TblRideRequest.RequestCreateDate'</summary>
		public System.DateTime RequestCreateDate { get; set; }
		
		/// <summary>Gets the RequestEndAddressGuid field. Mapped onto 'TblRideRequest.RequestEndAddressGuid'</summary>
		public System.Guid RequestEndAddressGuid { get; set; }
		
		/// <summary>Gets the RequestEndDateTime field. Mapped onto 'TblRideRequest.RequestEndDateTime'</summary>
		public System.DateTime RequestEndDateTime { get; set; }
		
		/// <summary>Gets the RequestFromGuid field. Mapped onto 'TblRideRequest.RequestFromGuid'</summary>
		public System.Guid RequestFromGuid { get; set; }
		
		/// <summary>Gets the RequestStartAddressGuid field. Mapped onto 'TblRideRequest.RequestStartAddressGuid'</summary>
		public System.Guid RequestStartAddressGuid { get; set; }
		
		/// <summary>Gets the RequestStartDateTime field. Mapped onto 'TblRideRequest.RequestStartDateTime'</summary>
		public System.DateTime RequestStartDateTime { get; set; }
		
		/// <summary>Gets the RequestToGuid field. Mapped onto 'TblRideRequest.RequestToGuid'</summary>
		public System.Guid RequestToGuid { get; set; }
		
		/// <summary>Gets the RequestUpdateDate field. Mapped onto 'TblRideRequest.RequestUpdateDate'</summary>
		public System.DateTime RequestUpdateDate { get; set; }
		
		/// <summary>Gets the RideRequestGuid field. Mapped onto 'TblRideRequest.RideRequestGuid'</summary>
		public System.Guid RideRequestGuid { get; set; }
		
		/// <summary>Gets the EmailAddress field. Mapped onto 'TblUser.EmailAddress'</summary>
		public System.String EmailAddress { get; set; }
		
		/// <summary>Gets the Password field. Mapped onto 'TblUser.Password'</summary>
		public System.String Password { get; set; }
		
		/// <summary>Gets the UserCreateDate field. Mapped onto 'TblUser.UserCreateDate'</summary>
		public Nullable<System.DateTime> UserCreateDate { get; set; }
		
		/// <summary>Gets the UserGuid2 field. Mapped onto 'TblUser.UserGuid'</summary>
		public System.Guid UserGuid2 { get; set; }
		
		/// <summary>Gets the UserName field. Mapped onto 'TblUser.UserName'</summary>
		public System.String UserName { get; set; }
		
		/// <summary>Gets the UserUpdateDate field. Mapped onto 'TblUser.UserUpdateDate'</summary>
		public Nullable<System.DateTime> UserUpdateDate { get; set; }
		
	}
}
