//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.6.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace RideShare.LLBLGEN.EntityClasses
{
	/// <summary>Class which represents the entity 'Tbladdress'.</summary>
	public partial class Tbladdress : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="Tbladdress"/> class.</summary>
		public Tbladdress() : base()
		{
			this.TblRides = new List<TblRide>();
			this.TblRides1 = new List<TblRide>();
			this.TblRideRequests = new List<TblRideRequest>();
			this.TblRideRequests1 = new List<TblRideRequest>();
			OnCreated();
		}

		/// <summary>Gets or sets the AddressCreateDate field. </summary>
		public System.DateTime AddressCreateDate { get; set;}
		/// <summary>Gets or sets the AddressGuid field. </summary>
		public System.Guid AddressGuid { get; set;}
		/// <summary>Gets or sets the AddressUpdateDate field. </summary>
		public System.DateTime AddressUpdateDate { get; set;}
		/// <summary>Gets or sets the City field. </summary>
		public System.String City { get; set;}
		/// <summary>Gets or sets the PostalCode field. </summary>
		public Nullable<System.Int32> PostalCode { get; set;}
		/// <summary>Gets or sets the State field. </summary>
		public System.String State { get; set;}
		/// <summary>Gets or sets the Street1 field. </summary>
		public System.String Street1 { get; set;}
		/// <summary>Gets or sets the Street2 field. </summary>
		public System.String Street2 { get; set;}
		/// <summary>Gets or sets the UserGuid field. </summary>
		public System.Guid UserGuid { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblRide.Tbladdress - Tbladdress.TblRides (m:1)'</summary>
		public virtual List<TblRide> TblRides { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblRide.Tbladdress1 - Tbladdress.TblRides1 (m:1)'</summary>
		public virtual List<TblRide> TblRides1 { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblRideRequest.Tbladdress - Tbladdress.TblRideRequests (m:1)'</summary>
		public virtual List<TblRideRequest> TblRideRequests { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblRideRequest.Tbladdress1 - Tbladdress.TblRideRequests1 (m:1)'</summary>
		public virtual List<TblRideRequest> TblRideRequests1 { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Tbladdress.TblUser - TblUser.Tbladdresses (m:1)'</summary>
		public virtual TblUser TblUser { get; set;}
	}
}
