//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.6.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace RideShare.LLBLGEN.EntityClasses
{
	/// <summary>Class which represents the entity 'Tblcontact'.</summary>
	public partial class Tblcontact : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="Tblcontact"/> class.</summary>
		public Tblcontact() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the ContactCreateDate field. </summary>
		public System.DateTime ContactCreateDate { get; set;}
		/// <summary>Gets or sets the ContactGuid field. </summary>
		public System.Guid ContactGuid { get; set;}
		/// <summary>Gets or sets the ContactType field. </summary>
		public Nullable<System.Guid> ContactType { get; set;}
		/// <summary>Gets or sets the ContactUpdateDate field. </summary>
		public System.DateTime ContactUpdateDate { get; set;}
		/// <summary>Gets or sets the ContactValue field. </summary>
		public System.String ContactValue { get; set;}
		/// <summary>Gets or sets the IsActive field. </summary>
		public System.String IsActive { get; set;}
		/// <summary>Gets or sets the UserGuid field. </summary>
		public System.Guid UserGuid { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Tblcontact.TblContactType - TblContactType.Tblcontacts (m:1)'</summary>
		public virtual TblContactType TblContactType { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Tblcontact.TblUser - TblUser.Tblcontacts (m:1)'</summary>
		public virtual TblUser TblUser { get; set;}
	}
}
