//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.6.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace RideShare.LLBLGEN.EntityClasses
{
	/// <summary>Class which represents the entity 'TblContactType'.</summary>
	public partial class TblContactType : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TblContactType"/> class.</summary>
		public TblContactType() : base()
		{
			this.Tblcontacts = new List<Tblcontact>();
			OnCreated();
		}

		/// <summary>Gets or sets the ContactType field. </summary>
		public System.String ContactType { get; set;}
		/// <summary>Gets or sets the ContactTypeCreateDate field. </summary>
		public System.DateTime ContactTypeCreateDate { get; set;}
		/// <summary>Gets or sets the ContactTypeGuid field. </summary>
		public System.Guid ContactTypeGuid { get; set;}
		/// <summary>Gets or sets the ContactTypeUpdateDate field. </summary>
		public System.DateTime ContactTypeUpdateDate { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Tblcontact.TblContactType - TblContactType.Tblcontacts (m:1)'</summary>
		public virtual List<Tblcontact> Tblcontacts { get; set;}
	}
}
