//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.6.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace RideShare.LLBLGEN.EntityClasses
{
	/// <summary>Class which represents the entity 'TblRide'.</summary>
	public partial class TblRide : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TblRide"/> class.</summary>
		public TblRide() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the RideCreateDate field. </summary>
		public System.DateTime RideCreateDate { get; set;}
		/// <summary>Gets or sets the RideEndAddressGuid field. </summary>
		public System.Guid RideEndAddressGuid { get; set;}
		/// <summary>Gets or sets the RideEndDateTime field. </summary>
		public System.DateTime RideEndDateTime { get; set;}
		/// <summary>Gets or sets the RideFromGuid field. </summary>
		public System.Guid RideFromGuid { get; set;}
		/// <summary>Gets or sets the RideGuid field. </summary>
		public System.Guid RideGuid { get; set;}
		/// <summary>Gets or sets the RideStartAddressGuid field. </summary>
		public System.Guid RideStartAddressGuid { get; set;}
		/// <summary>Gets or sets the RideStartDateTime field. </summary>
		public System.DateTime RideStartDateTime { get; set;}
		/// <summary>Gets or sets the RideToGuid field. </summary>
		public System.Guid RideToGuid { get; set;}
		/// <summary>Gets or sets the RideUpdateDate field. </summary>
		public System.DateTime RideUpdateDate { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblRide.Tbladdress - Tbladdress.TblRides (m:1)'</summary>
		public virtual Tbladdress Tbladdress { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblRide.Tbladdress1 - Tbladdress.TblRides1 (m:1)'</summary>
		public virtual Tbladdress Tbladdress1 { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblRide.TblUser - TblUser.TblRides (m:1)'</summary>
		public virtual TblUser TblUser { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblRide.TblUser1 - TblUser.TblRides1 (m:1)'</summary>
		public virtual TblUser TblUser1 { get; set;}
	}
}
