//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.6.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace RideShare.LLBLGEN.EntityClasses
{
	/// <summary>Class which represents the entity 'TblRideRequest'.</summary>
	public partial class TblRideRequest : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TblRideRequest"/> class.</summary>
		public TblRideRequest() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the RequestCreateDate field. </summary>
		public System.DateTime RequestCreateDate { get; set;}
		/// <summary>Gets or sets the RequestEndAddressGuid field. </summary>
		public System.Guid RequestEndAddressGuid { get; set;}
		/// <summary>Gets or sets the RequestEndDateTime field. </summary>
		public System.DateTime RequestEndDateTime { get; set;}
		/// <summary>Gets or sets the RequestFromGuid field. </summary>
		public System.Guid RequestFromGuid { get; set;}
		/// <summary>Gets or sets the RequestStartAddressGuid field. </summary>
		public System.Guid RequestStartAddressGuid { get; set;}
		/// <summary>Gets or sets the RequestStartDateTime field. </summary>
		public System.DateTime RequestStartDateTime { get; set;}
		/// <summary>Gets or sets the RequestToGuid field. </summary>
		public System.Guid RequestToGuid { get; set;}
		/// <summary>Gets or sets the RequestUpdateDate field. </summary>
		public System.DateTime RequestUpdateDate { get; set;}
		/// <summary>Gets or sets the RideRequestGuid field. </summary>
		public System.Guid RideRequestGuid { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblRideRequest.Tbladdress - Tbladdress.TblRideRequests (m:1)'</summary>
		public virtual Tbladdress Tbladdress { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblRideRequest.Tbladdress1 - Tbladdress.TblRideRequests1 (m:1)'</summary>
		public virtual Tbladdress Tbladdress1 { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblRideRequest.TblUser - TblUser.TblRideRequests (m:1)'</summary>
		public virtual TblUser TblUser { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblRideRequest.TblUser1 - TblUser.TblRideRequests1 (m:1)'</summary>
		public virtual TblUser TblUser1 { get; set;}
	}
}
