//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.6.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace RideShare.LLBLGEN.EntityClasses
{
	/// <summary>Class which represents the entity 'TblUser'.</summary>
	public partial class TblUser : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TblUser"/> class.</summary>
		public TblUser() : base()
		{
			this.Tbladdresses = new List<Tbladdress>();
			this.Tblcontacts = new List<Tblcontact>();
			this.TblRides = new List<TblRide>();
			this.TblRides1 = new List<TblRide>();
			this.TblRideRequests = new List<TblRideRequest>();
			this.TblRideRequests1 = new List<TblRideRequest>();
			OnCreated();
		}

		/// <summary>Gets or sets the EmailAddress field. </summary>
		public System.String EmailAddress { get; set;}
		/// <summary>Gets or sets the Password field. </summary>
		public System.String Password { get; set;}
		/// <summary>Gets or sets the UserCreateDate field. </summary>
		public Nullable<System.DateTime> UserCreateDate { get; set;}
		/// <summary>Gets or sets the UserGuid field. </summary>
		public System.Guid UserGuid { get; set;}
		/// <summary>Gets or sets the UserName field. </summary>
		public System.String UserName { get; set;}
		/// <summary>Gets or sets the UserUpdateDate field. </summary>
		public Nullable<System.DateTime> UserUpdateDate { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Tbladdress.TblUser - TblUser.Tbladdresses (m:1)'</summary>
		public virtual List<Tbladdress> Tbladdresses { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Tblcontact.TblUser - TblUser.Tblcontacts (m:1)'</summary>
		public virtual List<Tblcontact> Tblcontacts { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblRide.TblUser - TblUser.TblRides (m:1)'</summary>
		public virtual List<TblRide> TblRides { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblRide.TblUser1 - TblUser.TblRides1 (m:1)'</summary>
		public virtual List<TblRide> TblRides1 { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblRideRequest.TblUser - TblUser.TblRideRequests (m:1)'</summary>
		public virtual List<TblRideRequest> TblRideRequests { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblRideRequest.TblUser1 - TblUser.TblRideRequests1 (m:1)'</summary>
		public virtual List<TblRideRequest> TblRideRequests1 { get; set;}
	}
}
