//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.6.</auto-generated>
//------------------------------------------------------------------------------
using System;

namespace RideShare.LLBLGEN.TypedViewClasses
{
	/// <summary>Class which represents a row in the typedView 'TblContactType1'.</summary>
	public partial class TblContactType1TypedViewRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="TblContactType1TypedViewRow"/> class.</summary>
		public TblContactType1TypedViewRow()
		{
			OnCreated();
		}
		
		/// <summary>Gets or sets the ContactType field. </summary>
		public System.String ContactType { get; set; }
		/// <summary>Gets or sets the ContactTypeCreateDate field. </summary>
		public System.DateTime ContactTypeCreateDate { get; set; }
		/// <summary>Gets or sets the ContactTypeGuid field. </summary>
		public System.Guid ContactTypeGuid { get; set; }
		/// <summary>Gets or sets the ContactTypeUpdateDate field. </summary>
		public System.DateTime ContactTypeUpdateDate { get; set; }
	}
}
