//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.6.</auto-generated>
//------------------------------------------------------------------------------
using System;

namespace RideShare.LLBLGEN.TypedViewClasses
{
	/// <summary>Class which represents a row in the typedView 'TblRideRequest1'.</summary>
	public partial class TblRideRequest1TypedViewRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="TblRideRequest1TypedViewRow"/> class.</summary>
		public TblRideRequest1TypedViewRow()
		{
			OnCreated();
		}
		
		/// <summary>Gets or sets the RequestCreateDate field. </summary>
		public System.DateTime RequestCreateDate { get; set; }
		/// <summary>Gets or sets the RequestEndAddressGuid field. </summary>
		public System.Guid RequestEndAddressGuid { get; set; }
		/// <summary>Gets or sets the RequestEndDateTime field. </summary>
		public System.DateTime RequestEndDateTime { get; set; }
		/// <summary>Gets or sets the RequestFromGuid field. </summary>
		public System.Guid RequestFromGuid { get; set; }
		/// <summary>Gets or sets the RequestStartAddressGuid field. </summary>
		public System.Guid RequestStartAddressGuid { get; set; }
		/// <summary>Gets or sets the RequestStartDateTime field. </summary>
		public System.DateTime RequestStartDateTime { get; set; }
		/// <summary>Gets or sets the RequestToGuid field. </summary>
		public System.Guid RequestToGuid { get; set; }
		/// <summary>Gets or sets the RequestUpdateDate field. </summary>
		public System.DateTime RequestUpdateDate { get; set; }
		/// <summary>Gets or sets the RideRequestGuid field. </summary>
		public System.Guid RideRequestGuid { get; set; }
	}
}
