//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.6.</auto-generated>
//------------------------------------------------------------------------------
using System;

namespace RideShare.LLBLGEN.TypedViewClasses
{
	/// <summary>Class which represents a row in the typedView 'TblUser1'.</summary>
	public partial class TblUser1TypedViewRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="TblUser1TypedViewRow"/> class.</summary>
		public TblUser1TypedViewRow()
		{
			OnCreated();
		}
		
		/// <summary>Gets or sets the EmailAddress field. </summary>
		public System.String EmailAddress { get; set; }
		/// <summary>Gets or sets the Password field. </summary>
		public System.String Password { get; set; }
		/// <summary>Gets or sets the UserCreateDate field. </summary>
		public Nullable<System.DateTime> UserCreateDate { get; set; }
		/// <summary>Gets or sets the UserGuid field. </summary>
		public System.Guid UserGuid { get; set; }
		/// <summary>Gets or sets the UserName field. </summary>
		public System.String UserName { get; set; }
		/// <summary>Gets or sets the UserUpdateDate field. </summary>
		public Nullable<System.DateTime> UserUpdateDate { get; set; }
	}
}
